### ISSUE TITLE
how rule-based AI works

### ISSUE THREAD

**Issue by ziaoang** [BazkieBumpercar/GameplayFootball#7]
Hi BazkieBumpercar, your work is introduced in Google Research Football. Google trains a lot of AI to challenge your rule-based AI, but can not defeat your hardest AI. How do you design your rule-based AI, is there some papers or blobs?
Thanks~

**Comment by BazkieBumpercar** [comment]
Thank you for your question ziaoang!

My defensive system consists of various methods in a somewhat overly complicated combination. It was a while ago when I programmed that so I can't really explain it all too well. I think it's a combination of:

* hungarian algorithm, to find the best 'fit' for the current player's positions, into the formation setup (who is most fit to be left-back right now? or keeper? etc)
* man-marking system, where the most dangerous opponents are assigned to the player that have the most chance of reaching them before they have a chance to shoot
* magnets/anti-magnets system so that people are attracted to the ball, keep proper distance from teammates, etc.
* a lot of custom code to glue this all together

One thing I do remember is how much harder defensive systems are, as compared to offensive systems. It makes sense; an offensive mistake is not so bad, while a defensive mistake often leads to a goal.

I put *a lot* of time and effort into coming up with the eventual code, and I too am very happy with the result, it's pretty solid.

I haven't looked at google's code, so I can't say much about it. Maybe the difference is that I have a lot of experience with watching, playing, and thinking about football == experience, while they are programmers first, not football fans (I'm not sure about that, of course :)).

I think that a machine learning AI could potentially be better at football defense than my rule-based code. But the latter is still preferred, since it's easier to change, maintain etc (since you can control every part of it. neural networks are more 'black box-y')

**Comment by ziaoang** [comment]
Thanks, this is a wonderful work!
